title: Electronthemes Docs
email: electronthemes@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Electronthemes docs provides online documentaion of all the themes of Electronthemes market. We sell responsive wordpress and ghost themes.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: electronthemes1
github_username: electronthemes

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed

# - sass
sass:
    sass_dir: styles

# Do NOT do this. This is WRONG!!
exclude:
    - [vendor]
    - Gemfile
    - Gemfile.lock
    - node_modules
    - gulpfile.js
    - package.json
